// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun run prisma/seed.ts",
  },
  datasource: {
    // CLI operations (migrate, db pull, studio) use the direct connection —
    // Supabase's pooled DATABASE_URL (pgbouncer transaction mode) doesn't
    // support the advisory locks/prepared statements these commands need.
    // The app's runtime client (app/api/prisma/client.ts) uses DATABASE_URL instead.
    url: process.env["DIRECT_URL"],
  },
});
