import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f8f9fa',
        'secondary': '#525e79',
        'on-secondary-fixed': '#0e1b33',
        'outline-variant': '#c7c6cd',
        'on-error-container': '#93000a',
        'tertiary-container': '#3b3118',
        'on-primary-fixed': '#171b2b',
        'on-secondary-container': '#54617c',
        'inverse-surface': '#2e3132',
        'background': '#f8f9fa',
        'surface-container': '#edeeef',
        'on-tertiary-container': '#a89978',
        'inverse-primary': '#c2c5db',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e7e8e9',
        'surface-dim': '#d9dadb',
        'surface-container-low': '#f3f4f5',
        'secondary-fixed-dim': '#b9c7e6',
        'primary-container': '#2d3142',
        'on-secondary': '#ffffff',
        'surface': '#f8f9fa',
        'tertiary': '#251c06',
        'primary': '#181c2c',
        'surface-tint': '#5a5d70',
        'tertiary-fixed-dim': '#d5c5a2',
        'on-background': '#191c1d',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#9599ad',
        'on-primary': '#ffffff',
        'secondary-fixed': '#d7e2ff',
        'secondary-container': '#d0ddfd',
        'surface-container-highest': '#e1e3e4',
        'outline': '#77767d',
        'surface-variant': '#e1e3e4',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'primary-fixed': '#dee1f8',
        'on-secondary-fixed-variant': '#3a4760',
        'tertiary-fixed': '#f2e1bc',
        'on-tertiary-fixed-variant': '#51462b',
        'inverse-on-surface': '#f0f1f2',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#424658',
      },
      spacing: {
        sm: '12px',
        gutter: '16px',
        lg: '40px',
        margin_desktop: '48px',
        md: '24px',
        xl: '64px',
        margin_mobile: '20px',
        base: '8px',
        xs: '4px',
      },
      fontFamily: {
        serif: ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        h3: ['20px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

export default config;
